// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDUVRSyECkOnxuu-gALGUqR5sRqonDWnw',
    appId: '1:844099394384:web:b530ca27311b92b34eea55',
    messagingSenderId: '844099394384',
    projectId: 'penyewaan-lapangan-64a01',
    authDomain: 'penyewaan-lapangan-64a01.firebaseapp.com',
    storageBucket: 'penyewaan-lapangan-64a01.firebasestorage.app',
    measurementId: 'G-Y5GZE9XRZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMctzev8eAbtL-90qWCoypkOA_7_t8kPw',
    appId: '1:844099394384:android:7a0d3f658950910a4eea55',
    messagingSenderId: '844099394384',
    projectId: 'penyewaan-lapangan-64a01',
    storageBucket: 'penyewaan-lapangan-64a01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1jLZSpOhlpX8R1d0giy5JFjbkFOchekY',
    appId: '1:844099394384:ios:67928054aa2dedb54eea55',
    messagingSenderId: '844099394384',
    projectId: 'penyewaan-lapangan-64a01',
    storageBucket: 'penyewaan-lapangan-64a01.firebasestorage.app',
    androidClientId: '844099394384-3ta3p6ve22cq5784nkn1neipq6rft0r2.apps.googleusercontent.com',
    iosClientId: '844099394384-bdqskphuvssj89b9kkbhe9iguef611lu.apps.googleusercontent.com',
    iosBundleId: 'com.example.penyewaanLapangan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1jLZSpOhlpX8R1d0giy5JFjbkFOchekY',
    appId: '1:844099394384:ios:67928054aa2dedb54eea55',
    messagingSenderId: '844099394384',
    projectId: 'penyewaan-lapangan-64a01',
    storageBucket: 'penyewaan-lapangan-64a01.firebasestorage.app',
    androidClientId: '844099394384-3ta3p6ve22cq5784nkn1neipq6rft0r2.apps.googleusercontent.com',
    iosClientId: '844099394384-bdqskphuvssj89b9kkbhe9iguef611lu.apps.googleusercontent.com',
    iosBundleId: 'com.example.penyewaanLapangan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDUVRSyECkOnxuu-gALGUqR5sRqonDWnw',
    appId: '1:844099394384:web:b4c80681b6ab155b4eea55',
    messagingSenderId: '844099394384',
    projectId: 'penyewaan-lapangan-64a01',
    authDomain: 'penyewaan-lapangan-64a01.firebaseapp.com',
    storageBucket: 'penyewaan-lapangan-64a01.firebasestorage.app',
    measurementId: 'G-8WMVRD0LTM',
  );

}